:PROPERTIES:
#+TITLE: Publications
#+AUTHOR: Spencer A. Hill
#+OPTIONS: toc:nil ':nil num:nil
#+OPTIONS: texht:t
#+LATEX_CLASS: shillcv
#+LATEX_CLASS_OPTIONS: [12pt,letterpaper]
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \usepackage{tabularx}
#+LATEX_HEADER: \setlength{\parindent}{0pt}

#+LATEX_HEADER: \usepackage{doi}

#+LATEX_HEADER_EXTRA:

#+MACRO: LINK @@html:<a href=$1>$2</a>@@
:END:
** In preparation
1. *Hill, Spencer A.*, Yi Ming, Isaac M. Held, and Ming Zhao.  "Robust responses
   of the Sahelian hydrological cycle to global warming."
2. *Hill, Spencer A.*, Juan M. Lora, Norris Khoo, Sean P. Faulk, and Jonathan
   Aurnou.  "DIYnamics: scalable geoscience education via rotating fluid
   demonstrations."  Proposal approved for submission to /Bulletin of the
   American Meteorological Society/.
3. Smyth, Jane, *Spencer A. Hill*, and Yi Ming.  "Simulated tropical circulation
   responses to orbital precession and their sensitivity to ocean
   thermodynamics."
** COMMENT Submitted/in revision
** Peer-reviewed
1. (2017) Brown, Patrick T., Yi Ming, Wenhong Li, and *Spencer A. Hill*.  "Change
   in the magnitude and mechanisms of unforced low-frequency surface temperature
   variability in a warmer climate."  Accepted, /Nature Climate Change/.  doi:
   [[https://doi.org/10.1038/nclimate3381][10.1038/nclimate3381]].  {{{LINK("papers/brown+2017nature_cc.pdf", PDF.)}}}
   {{{LINK("https://nicholas.duke.edu/about/news/warmer-world-may-bring-more-local-less-global-temperature-variability", Duke University press release.)}}}
2. (2017) Jeevanjee, Nadir, Pedram Hassanzadeh, *Spencer A. Hill*, and Aditi
   Sheshadri.  "A perspective on climate model hierarchies."  Accepted, /Journal
   of Advances in Modeling Earth Systems/.  doi: [[doi:10.1002/2017MS001038][10.1002/2017MS001038]].
   {{{LINK("papers/jeevanjee+2017hierarchies_accepted.pdf", PDF.)}}}
3. (2017) *Hill, Spencer A.*, Yi Ming, Isaac M. Held, and Ming Zhao.  "A moist
   static energy budget-based analysis of the Sahel rainfall response to uniform
   oceanic warming."  /Journal of Climate/, *30*, 5637-5660.  doi:
   [[doi:10.1175/JCLI-D-16-0785.1][10.1175/JCLI-D-16-0785.1]].  {{{LINK("papers/2017sahel_mse_precip.pdf", PDF.)}}}
4. (2015) *Hill, Spencer A.*, Yi Ming, and Isaac M. Held.  "Mechanisms of forced
   tropical meridional energy flux change."  /Journal of Climate/, *28*, 1725-1742.
   doi: [[http://dx.doi.org/10.1175/JCLI-D-14-00165.1][10.1175/JCLI-D-14-00165.1]].
   {{{LINK("papers/hill+2015_full_with_corr.pdf", PDF.)}}}
   + Corrigendum: [[https://dx.doi.org/10.1175/JCLI-D-16-0485.1]].
     {{{LINK("papers/hill+2015corr.pdf", PDF.)}}}
5. (2012) *Hill, Spencer A.* and Yi Ming.  "Nonlinear climate response to regional
   brightening of tropical marine stratocumulus."  /Geophysical Research Letters/,
   *39*, L15707, 5 pp. doi:
   [[http://dx.doi.org/10.1029/2012GL052064][10.1029/2012GL052064]]. {{{LINK("papers/hill+ming2012.pdf", PDF.)}}}
   {{{LINK("papers/hill+ming2012supp.pdf", Supplementary material PDF.)}}}
** PhD thesis
(2016) *Hill, Spencer A.* "Energetic and hydrological responses of Hadley
circulations and the African Sahel to sea surface temperature perturbations."
PhD Thesis, Princeton University Program in Atmospheric and Oceanic Sciences.
{{{LINK("papers/spencer_hill_phd_thesis.pdf", PDF.)}}}
** Non peer-reviewed
1. (2017) *Hill, Spencer A.* and Spencer K. Clark.  "What’s needed for the Future
   of AOS Python? Tools for Automating AOS Data Analysis and Management."
   Invited guest blog post on "PyAOS" blog.  URL:
   http://pyaos.johnny-lin.com/?p=1546.
2. (2012) *Hill, Spencer A.*  "A head in the clouds elucidates climate" (book
   review of [[http://press.princeton.edu/titles/9773.html][/Atmosphere, Clouds, and Climate/]] by David Randall). /Science/, *337*,
   1 pp., doi: [[http://dx.doi.org/10.1126/science.1225615][10.1126/science.1225615]].  {{{LINK("papers/hill2012.pdf", PDF.)}}}
** Technical/software
1. (2017) Hill, Spencer A. and Spencer Clark.  "aospy: automated climate data
   analysis and management."  [[http://aospy.readthedocs.io/en/latest/]].
2. (2016) Hoyer, Stephan et al.  "xarray: v0.8.0."  doi: [[doi:10.5281/zenodo.59499][10.5281/zenodo.59499]].
