** In preparation
1. *Hill, Spencer A.*, Yi Ming, Isaac M. Held, and Ming Zhao.  "Towards emergent
   constraints on future rainfall in the Sahel."  In preparation.
2. Smyth, Jane, *Spencer A. Hill*, and Yi Ming.  "Simulated tropical circulation
   responses to orbital precession and their sensitivity to ocean
   thermodynamics."  In preparation.
** Submitted/in revision/in press.
1. *Hill, Spencer A.*, Yi Ming, Isaac M. Held, and Ming Zhao.  "A moist static
   energy budget-based analysis of the Sahel rainfall response to uniform
   oceanic warming."  Submitted to /Journal of Climate/
2. Brown, Patrick T., Yi Ming, Wenhong Li, and *Spencer A. Hill*.  "Change in the
   magnitude and mechanisms of unforced low-frequency surface temperature
   variability in a warmer climate."  Submitted to /Nature Climate Change/.
** Peer-reviewed
1. (2015) *Hill, Spencer A.*, Yi Ming, and Isaac M. Held. "Mechanisms of forced tropical
   meridional energy flux change."  /J. Climate/, *28*, 1725-1742.  doi:
   [[http://dx.doi.org/10.1175/JCLI-D-14-00165.1][10.1175/JCLI-D-14-00165.1]] and [[http://journals.ametsoc.org/doi/abs/10.1175/JCLI-D-16-0485.1][Corrigendum]].
2. (2012) *Hill, Spencer A.* and Yi Ming. "Nonlinear climate response to regional
   brightening of tropical marine stratocumulus."  /Geophysical Research Letters/,
   *39*, L15707, 5 pp. doi: [[http://dx.doi.org/10.1029/2012GL052064][10.1029/2012GL052064]].
** Non peer-reviewed
1. (2012) *Hill, Spencer A.* "A head in the clouds elucidates" (book review of
   [[http://press.princeton.edu/titles/9773.html][Atmosphere, Clouds, and Climate]] by David Randall). /Science/, *337*, 1 pp., doi:
   [[http://dx.doi.org/10.1126/science.1225615][10.1126/science.1225615]].
** PhD thesis
(2016) *Hill, Spencer A.* "Energetic and hydrological responses of Hadley
circulations and the African Sahel to sea surface temperature perturbations."
PhD Thesis, Princeton University Program in Atmospheric and Oceanic Sciences.
Defended [2016-08-02 Tue].  [[http://search.proquest.com.ezproxy.princeton.edu/pqdtglobal/docview/1831357756/abstract/522E2D42A8BF49C0PQ/1][Proquest version]].  @@html:<a
href="files/spencer_hill_phd_thesis.pdf">PDF version</a>.@@
** Technical/software
1. (2016) Hoyer, Stephan et al.  "xarray: v0.8.0."  [[doi:10.5281/zenodo.59499][10.5281/zenodo.59499]].
